name: Build CoreDNS With PForward

on:
  push:
    tags:
      - "*"

jobs:
  Build-CoreDNS-With-PForward:
    runs-on: ubuntu-latest
    steps:
      - name: Clone PForward
        uses: actions/checkout@v4
      
      - name: Set Go Version
        run: |
          make clone-dependency
          echo "GO_VERSION=$(make go-version)" >> $GITHUB_ENV

      - name: Prepare Golang
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
          cache-dependency-path: |
            coredns/go.sum
            pforward/go.sum

      - name: Prepare QEMU
        uses: docker/setup-qemu-action@v3

      - name: Prepare Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build CoreDNS
        run: |
          make prepare-docker

      - name: Login GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          context: .
          push: true
          tags: ghcr.io/newcoderlife/coredns:latest
          no-cache: true

      - name: Test Docker Image
        if: ${{ success() }}
        run: |
          make test
          make save-image

      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            *.deb
            *.tar